Task10 - initial commit
jb-user/API pull request #1
Opened 2023-03-10 07:07 UTC by jb-user

Task 10 - https://coherentsolutions.sharepoint.com/:w:/r/sites/training-center/_layouts/15/Doc.aspx?sourcedoc=%7B3A2E4457-28B3-49BF-AB13-F9B8AC1CAC2A%7D&file=Task10.docx&action=default&mobileredirect=true

2023-03-10 10:00 UTC, shukal94 requested changes

2023-03-10 10:00 UTC, shukal94 commented on src/main/java/com/coherent/api/training/TokenManager.java
> +    public static TokenManager getInstance() {
let's add synchronized to make your singleton thread-safe

2023-03-10 10:00 UTC, shukal94 commented on src/main/java/com/coherent/api/training/MyHttpClient.java
> +    public String executeRequest(HttpRequestBase request) {
probably we have to add capability to send unauthorized requests, so let's remove token setup from this method

2023-03-10 10:00 UTC, shukal94 commented on src/main/java/com/coherent/api/training/TokenManager.java
> +        try (CloseableHttpClient httpClient = HttpClientBuilder.create().build()) {
let's move urls, creds, params to properties file

2023-03-10 10:00 UTC, shukal94 commented on src/main/java/com/coherent/api/training/TokenManager.java
> +            readToken = getToken("read");
let's define enum with scope values

2023-03-10 10:00 UTC, shukal94 commented on src/main/java/com/coherent/api/training/MyHttpClient.java
> +public class MyHttpClient {
let's call it CustomHttpClient

2023-03-10 10:00 UTC, shukal94 commented on src/test/java/com/coherent/api/training/ApiTests.java
> +        HttpGet getRequest = new HttpGet("http://localhost:8888/swagger-ui/");
let's move url to properties file and add at least one validation to test

2023-03-16 14:04 UTC, jb-user commented on src/test/java/com/coherent/api/training/ApiTests.java
> +        HttpGet getRequest = new HttpGet("http://localhost:8888/swagger-ui/");
code updated, please review

2023-03-16 15:07 UTC, shukal94 requested changes

2023-03-16 15:07 UTC, shukal94 commented on src/main/java/com/coherent/api/training/CustomHttpClient.java
> +    public static HttpResponse executePost(String endpoint) {
I think for post in future we'll need more parameters

2023-03-23 06:02 UTC, shukal94 requested changes

2023-03-23 06:02 UTC, shukal94 commented on src/main/java/com/coherent/api/training/auth/AuthTokenResponse.java
> +public class AuthTokenResponse {
move this class to model package

2023-03-23 06:02 UTC, shukal94 commented on src/main/java/com/coherent/api/training/enums/Scope.java
> +package com.coherent.api.training.enums;
it's not a good practice to have a separate enums package, it is model as well, so let's move all of your enums to model package

2023-03-23 07:56 UTC, jb-user commented on src/main/java/com/coherent/api/training/enums/Scope.java
> +package com.coherent.api.training.enums;
fixed

2023-03-23 08:35 UTC, shukal94 approved these changes

2023-03-23 09:07 UTC, merged